apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: external-ingress-demo
  component: example2

resources:
- ../base

nameSuffix: -example2

configMapGenerator:
  - name: demo-content
    behavior: replace
    files:
      - content/index.html

patches:
  - patch: |
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: external-ingress-demo
      spec:
        host: demo-example2.apps.shift.nerc.mghpcc.org
